apiVersion : apps/v1
kind: Deployment
metadata:
  name: "myaks-5cf6"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "myaks-5cf6"
  template:
    metadata:
      labels:
        app: "myaks-5cf6"
    spec:
      containers:
        - name: "myaks-5cf6"
          image: "myacrpng.azurecr.io/myaks"
          ports:
          - containerPort: 80
