apiVersion: v1
kind: Service
metadata:
    name: "myaks-5cf6"
    labels:
        app: "myaks-5cf6"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "myaks-5cf6"