on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: myacrpng.azurecr.io
        username: ${{ secrets.acr_myacrpng_username }}
        password: ${{ secrets.acr_myacrpng_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t myacrpng.azurecr.io/myaks:${{ github.sha }}
        docker push myacrpng.azurecr.io/myaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_myaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep myaks17dc | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace myaks17dc`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: myaks17dc
        container-registry-url: myacrpng.azurecr.io
        container-registry-username: ${{ secrets.acr_myacrpng_username }}
        container-registry-password: ${{ secrets.acr_myacrpng_password }}
        secret-name: myaksdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: myaks17dc
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          myacrpng.azurecr.io/myaks:${{ github.sha }}
        imagepullsecrets: |
          myaksdockerauth